import Head from 'next/head'
import { useRouter } from 'next/router'
import { Inter } from 'next/font/google'

export default function Home({ params }) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <h1>Course Page: {router.query.slug}</h1>
      </div>
    </>
  )
}
