import Head from "next/head";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Grid, GridItem, Center, SimpleGrid } from "@chakra-ui/react";

import { getSiteConfig } from "@/services/siteConfig";
import { getCourses } from "@/services/courses";

import Layout from "@/components/layout/layout";
import CourseCard from "@/components/courses/courseCard";
import ChakraPagination from "@/components/pagination";

import { usePagination } from "@ajna/pagination";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  const { siteConfig } = props;
  const [courses, setCourses] = useState();
  const [pagination, setPagination] = useState();
  const { pagesCount, currentPage, setCurrentPage, pages } = usePagination({
    pagesCount: pagination?.pagesCount,
    initialState: { currentPage: 1 },
  });

  useEffect(() => {
    const fetchData = async () => {
      const data = await getCourses(currentPage);
      setCourses(data.courses);
      setPagination(data.pagination);
    };
    fetchData();
  }, [currentPage]);

  return (
    <>
      <Head>
        <title>{siteConfig?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          {courses ? (
            <Grid>
              <GridItem my="2em">
                <SimpleGrid columns={[1, null, 3]} spacing='40px'>
                  {courses.map((course) => (
                      <CourseCard course={course} key={course?.id}/>
                  ))}
                </SimpleGrid>
              </GridItem>
              <Center>
                <ChakraPagination
                  pages={pages}
                  currentPage={currentPage}
                  pagesCount={pagesCount}
                  setCurrentPage={setCurrentPage}
                />
              </Center>
            </Grid>
          ) : (
            <p>No hay cursos</p>
          )}
      </Layout>
    </>
  );
}

// get static props with page info from backend
export async function getStaticProps() {
  const siteConfig = await getSiteConfig();
  return {
    props: {
      siteConfig: siteConfig,
    },
  };
}
