import Head from "next/head";
import NextLink from "next/link"
import {
  Stack,
  Flex,
  Button,
  Text,
  VStack,
  useBreakpointValue,
  useColorModeValue,
} from "@chakra-ui/react";
import { getSiteConfig } from "@/services/siteConfig";

export default function Home(props) {
  const { siteConfig } = props;
  
  return (
    <>
      <Head>
        <title>{siteConfig?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        w={"full"}
        h={"100vh"}
        backgroundImage={
          `url(${siteConfig?.home_background}})`
        }
        backgroundSize={"cover"}
        backgroundPosition={"center center"}
      >
        <VStack
          w={"full"}
          justify={"center"}
          px={useBreakpointValue({ base: 4, md: 8 })}
          bgGradient={"linear(to-r, blackAlpha.600, transparent)"}
        >
          <Stack maxW={"2xl"} align={"flex-start"} spacing={6}>
            <Text
              color={"white"}
              fontWeight={700}
              lineHeight={1.2}
              fontSize={useBreakpointValue({ base: "3xl", md: "4xl" })}
            >
              Bienvenid@ a {siteConfig?.title}
            </Text>
            <Stack direction={"row"}>
              <NextLink href="/auth/login">
                <Button
                  color={"black"}
                  bg={"white"}
                  rounded={'.25rem'}
                  border={'1px'}
                  borderColor="black"
                  _hover={{
                    transform: `translate(-.25rem, -.25rem)`,
                    bg:"gray.600",
                    color: "white",
                    boxShadow: ".25rem .25rem 0 black"
                  }}
                >
                  Iniciar sesión
                </Button>
              </NextLink>    
              <NextLink href="/auth/register">       
                <Button
                  color={"black"}
                  bg={"whiteAlpha.500"}
                  rounded={'.25rem'}
                  border={'1px'}
                  borderColor="black"
                  _hover={{ 
                    transform: `translate(-.25rem, -.25rem)`,
                    bg: "whiteAlpha.700",
                    boxShadow: ".25rem .25rem 0 black" 
                  }}
                >
                  Registrarse
                </Button>
              </NextLink> 
            </Stack>
          </Stack>
        </VStack>
      </Flex>
    </>
  );
}

// get static props with page info from backend
export async function getStaticProps() {
  const siteConfig = await getSiteConfig();
  return {
    props: {
      siteConfig,
    },
  }
}
